//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredFlight
    {
        public int FlightId { get; set; }
        public string PlaneName { get; set; }
        public Nullable<decimal> TotalSeats { get; set; }
        public string FlightStartAirport { get; set; }
        public string FlightEndAirport { get; set; }
    }
}
